### PR TITLE
generate precompilation statements

### PR DESCRIPTION
**Pull request by Nayoth**
Using `SnoopCompile.jl` to gernerate precompile statements. Here is the time for building the package. 
```
julia> @time using InMemoryDatasets
[ Info: Precompiling InMemoryDatasets [5c01b14b-ab03-46ff-b164-14c663efdd9f]
 14.241571 seconds (2.22 M allocations: 157.196 MiB, 0.23% gc time, 0.48% compilation time: 19% of which was recompilation)
```
Here is the impact:

without precompilation:
```
julia> @time sort(ds, :);
  2.808788 seconds (13.99 M allocations: 831.252 MiB, 9.19% gc time, 98.64% compilation time: 0% of which was recompilation)

julia> @time transpose(ds, :);
  1.756015 seconds (8.00 M allocations: 606.615 MiB, 11.99% gc time, 85.74% compilation time: 1% of which was recompilation)

julia> @time closejoin(trades, quotes, on = :time, makeunique = true);
  5.680738 seconds (24.59 M allocations: 1.264 GiB, 8.70% gc time, 99.96% compilation time: 0% of which was recompilation)

julia> @time innerjoin(store, roster, on = [:store => :store, :date => (:start_date, nothing)]);
  7.583471 seconds (34.46 M allocations: 1.804 GiB, 9.84% gc time, 99.95% compilation time)
```

with precompilation:
```
julia> @time sort(ds, :);
  1.735795 seconds (3.01 M allocations: 251.664 MiB, 7.64% gc time, 94.94% compilation time)

julia> @time transpose(ds, :);
  1.073181 seconds (2.14 M allocations: 293.044 MiB, 13.29% gc time, 72.85% compilation time: 1% of which was recompilation)

julia> @time closejoin(trades, quotes, on = :time, makeunique = true);
  3.339037 seconds (4.72 M allocations: 247.872 MiB, 1.19% gc time, 99.92% compilation time: 0% of which was recompilation)

julia> @time innerjoin(store, roster, on = [:store => :store, :date => (:start_date, nothing)]);
  4.069992 seconds (6.61 M allocations: 345.980 MiB, 1.41% gc time, 99.92% compilation time: 0% of which was recompilation)
```

And the precompile won't effect the allocations:

without precompile:
```
julia> @time leftjoin(ds, ds1, on = :x1);
  4.579197 seconds (21.32 M allocations: 1.182 GiB, 8.52% gc time, 98.93% compilation time: 0% of which was recompilation)

julia> @time leftjoin(ds, ds1, on = :x1);
  0.025978 seconds (13.80 k allocations: 89.598 MiB)
```

with precompile:
```
julia> @time leftjoin(ds, ds1, on = :x1);
  2.428134 seconds (1.66 M allocations: 175.215 MiB, 98.95% compilation time)

julia> @time leftjoin(ds, ds1, on = :x1);
  0.025569 seconds (13.79 k allocations: 89.598 MiB)
```

### CODE REVIEW

**Comment by sl-solution** [comment]
Do you have a script for producing the precompilation file automatically, or it should be created manually? 
Please report the allocations for main operations like sort, groupby, gatherby, combine, leftjoin, innerjoin, outerjoin, update, compare, contain, closejoin, transpose.

I have previously seen huge amount of allocation by adding precompilation. This should have been fixed in Julia 1.8, however, we should be extra careful.

**Comment by Nayoth** [comment]
The precompile statements are generated by the `SnoopCompile.jl`. The code is generate by the "src/precompile/warmup.jl", and we should remove the function define code so the SnoopCompile gonna work.
```
using SnoopCompile
inf_timing = @snoopi tmin = 0.1 include("src/precompile/warmup.jl")
pc = SnoopCompile.parcel(inf_timing)
SnoopCompile.write("src/precompile/precompile_tmp.jl", pc[:DataFrames], always = true)
```

And here is the allocation without precompilation:
```
julia> @time sort(ds, :);
  2.830952 seconds (14.04 M allocations: 833.898 MiB, 9.54% gc time, 98.77% compilation time: 1% of which was recompilation)

julia> @time sort(ds, :);
  0.032776 seconds (9.37 k allocations: 94.693 MiB, 10.42% gc time)

julia> @time groupby(ds, 1);
  0.786925 seconds (1.83 M allocations: 101.939 MiB, 3.40% gc time, 99.81% compilation time)

julia> @time groupby(ds, 1);
  0.000724 seconds (474 allocations: 1.752 MiB)

julia> @time gatherby(ds, 1);
  1.429908 seconds (6.14 M allocations: 324.987 MiB, 5.61% gc time, 99.90% compilation time: 1% of which was recompilation)

julia> @time gatherby(ds, 1);
  0.000447 seconds (320 allocations: 412.477 KiB)

julia> @time combine(groupby(ds, :x1), :x2 => [IMD.sum, mean]);
  2.204251 seconds (6.24 M allocations: 333.816 MiB, 3.05% gc time, 99.70% compilation time: 1% of which was recompilation)

julia> @time combine(groupby(ds, :x1), :x2 => [IMD.sum, mean]);
  0.001593 seconds (1.23 k allocations: 2.670 MiB)

julia> @time leftjoin(ds, ds1, on = :x1);
  4.738023 seconds (21.33 M allocations: 1.183 GiB, 8.29% gc time, 99.09% compilation time: 0% of which was recompilation)

julia> @time leftjoin(ds, ds1, on = :x1);
  0.039483 seconds (13.76 k allocations: 89.597 MiB, 31.74% gc time)

julia> @time innerjoin(ds, ds1, on = :x1);
  4.584455 seconds (21.24 M allocations: 1.098 GiB, 8.31% gc time, 99.88% compilation time: 0% of which was recompilation)

julia> @time innerjoin(ds, ds1, on = :x1);
  0.004732 seconds (7.47 k allocations: 4.739 MiB)

julia> @time outerjoin(ds, ds1, on = :x1);
  4.893962 seconds (22.48 M allocations: 1.242 GiB, 8.45% gc time, 99.14% compilation time: 0% of which was recompilation)

julia> @time outerjoin(ds, ds1, on = :x1);
  0.034967 seconds (13.80 k allocations: 89.598 MiB, 26.83% gc time)

julia> @time update(ds, ds1, on = [:x1, :x2]);
  4.334985 seconds (20.62 M allocations: 1.151 GiB, 8.57% gc time, 99.05% compilation time: 0% of which was recompilation)

julia> @time update(ds, ds1, on = [:x1, :x2]);
  0.051509 seconds (858 allocations: 86.660 MiB, 51.76% gc time)

julia> @time compare(old, new,on = [1=>1,2=>2],cols = [:Amount=>:AMT, :Account_Id=>:Ac_Id],eq = eq_fun);
  7.132557 seconds (28.74 M allocations: 1.475 GiB, 10.19% gc time, 99.96% compilation time: 0% of which was recompilation)

julia> @time compare(old, new,on = [1=>1,2=>2],cols = [:Amount=>:AMT, :Account_Id=>:Ac_Id],eq = eq_fun);
  0.000607 seconds (1.72 k allocations: 164.453 KiB)

julia> @time contains(dsl, dsr, on = [1=>1, 2=>(2,3)], strict_inequality = true);
  7.063665 seconds (33.43 M allocations: 1.751 GiB, 9.71% gc time, 99.88% compilation time: 0% of which was recompilation)

julia> @time contains(dsl, dsr, on = [1=>1, 2=>(2,3)], strict_inequality = true);
  0.000345 seconds (683 allocations: 64.500 KiB)

julia> @time closejoin(ds, ds1, on = :x1);
  5.413706 seconds (23.55 M allocations: 1.299 GiB, 8.47% gc time, 99.05% compilation time: 0% of which was recompilation)

julia> @time closejoin(ds, ds1, on = :x1);
  0.027569 seconds (1.21 k allocations: 87.547 MiB)

julia> @time transpose(ds, :);
  1.747195 seconds (7.86 M allocations: 599.388 MiB, 12.06% gc time, 85.68% compilation time: 0% of which was recompilation)

julia> @time transpose(ds, :);
  0.219632 seconds (499.91 k allocations: 206.445 MiB, 31.26% gc time
```

Here is allocation for this PR:

```
julia> @time sort(ds, :);
  1.832809 seconds (3.01 M allocations: 251.159 MiB, 8.31% gc time, 94.12% compilation time: 0% of which was recompilation)

julia> @time sort(ds, :);
  0.033340 seconds (8.91 k allocations: 93.790 MiB, 15.41% gc time)

julia> @time groupby(ds, 1);
  0.818120 seconds (1.81 M allocations: 97.290 MiB, 7.74% gc time, 99.85% compilation time)

julia> @time groupby(ds, 1);
  0.000808 seconds (472 allocations: 1.752 MiB)

julia> @time gatherby(ds, 1);
  0.806852 seconds (911.99 k allocations: 47.113 MiB, 99.85% compilation time)

julia> @time gatherby(ds, 1);
  0.000474 seconds (318 allocations: 412.414 KiB)

julia> @time combine(groupby(ds, :x1), :x2 => [IMD.sum, mean]);
  1.990447 seconds (4.42 M allocations: 231.859 MiB, 4.07% gc time, 99.69% compilation time)

julia> @time combine(groupby(ds, :x1), :x2 => [IMD.sum, mean]);
  0.001410 seconds (1.23 k allocations: 2.670 MiB)

julia> @time leftjoin(ds, ds1, on = :x1);
  2.568778 seconds (1.67 M allocations: 175.964 MiB, 2.91% gc time, 98.99% compilation time)

julia> @time leftjoin(ds, ds1, on = :x1);
  0.027993 seconds (13.75 k allocations: 89.596 MiB)

julia> @time innerjoin(ds, ds1, on = :x1);
  2.450939 seconds (1.66 M allocations: 90.901 MiB, 3.03% gc time, 99.73% compilation time: 0% of which was recompilation)

julia> @time innerjoin(ds, ds1, on = :x1);
  0.005643 seconds (7.45 k allocations: 4.856 MiB)

julia> @time outerjoin(ds, ds1, on = :x1);
  2.865220 seconds (3.00 M allocations: 245.424 MiB, 5.25% gc time, 97.06% compilation time: 0% of which was recompilation)

julia> @time outerjoin(ds, ds1, on = :x1);
  0.026665 seconds (13.81 k allocations: 89.598 MiB)

julia> @time update(ds, ds1, on = [:x1, :x2]);
  2.513453 seconds (3.85 M allocations: 290.774 MiB, 5.51% gc time, 96.05% compilation time: 0% of which was recompilation)

julia> @time update(ds, ds1, on = [:x1, :x2]);
  0.024069 seconds (859 allocations: 86.660 MiB)

julia> @time compare(old, new,on = [1=>1,2=>2],cols = [:Amount=>:AMT, :Account_Id=>:Ac_Id],eq = eq_fun);
  5.023343 seconds (10.94 M allocations: 575.257 MiB, 5.85% gc time, 99.95% compilation time: 0% of which was recompilation)

julia> @time compare(old, new,on = [1=>1,2=>2],cols = [:Amount=>:AMT, :Account_Id=>:Ac_Id],eq = eq_fun);
  0.000508 seconds (1.72 k allocations: 164.484 KiB)

julia> @time contains(dsl, dsr, on = [1=>1, 2=>(2,3)], strict_inequality = true);
  3.485964 seconds (6.06 M allocations: 316.706 MiB, 1.56% gc time, 99.91% compilation time: 1% of which was recompilation)

julia> @time contains(dsl, dsr, on = [1=>1, 2=>(2,3)], strict_inequality = true);
  0.000609 seconds (679 allocations: 64.375 KiB)

julia> @time closejoin(ds, ds1, on = :x1);
  3.060696 seconds (3.76 M allocations: 286.402 MiB, 5.16% gc time, 96.49% compilation time: 0% of which was recompilation)

julia> @time closejoin(ds, ds1, on = :x1);
  0.027547 seconds (1.21 k allocations: 87.547 MiB)

julia> @time transpose(ds, :);
  1.076342 seconds (2.14 M allocations: 293.151 MiB, 13.71% gc time, 80.79% compilation time: 1% of which was recompilation)

julia> @time transpose(ds, :);
  0.159861 seconds (499.91 k allocations: 206.445 MiB)
```

As we can see, the precompile won't influence the allocations for all the main operations for julia 1.8.

**Comment by sl-solution** [comment]
> and we should remove the function define code so the SnoopCompile gonna work

what does it mean?

**Comment by Nayoth** [comment]
It's means we shoud remove "function warmup()" in the `warmup.jl` when gerneating the precompile statements. Cause @snoopi need to take a script that exercises the functions to generate precompile statements.

**Comment by sl-solution** [comment]
I see, 
@snoopi only checks the inference time, do you think using both @snoopc  and @snoopi can improve the latency even further?

**Comment by Nayoth** [comment]
I have tried to use `@snoopc` to generate precompile statements by:
```
julia> SnoopCompile.@snoopc "/tmp/IMD_compiles.log" begin
           using InMemoryDatasets, Pkg
           include(joinpath(dirname(dirname(pathof(InMemoryDatasets))), "src", "precompile", "warmup.jl"))
       end

data = SnoopCompile.read("/tmp/IMD_compiles.log")

SnoopCompile.write("/tmp/precompile", pc)
```
and it generated about five hundred precompile statements. The imapct on precompilation time is not significant, but it can reduce a lot allocations when first use these functions.

Here are some examples:
```
julia> @time using InMemoryDatasets
[ Info: Precompiling InMemoryDatasets [5c01b14b-ab03-46ff-b164-14c663efdd9f]
 26.941880 seconds (2.66 M allocations: 199.919 MiB, 0.21% gc time, 0.37% compilation time: 21% of which was recompilation)

julia> @time sort(ds, :);
  1.625532 seconds (1.36 M allocations: 166.658 MiB, 5.20% gc time, 92.83% compilation time: 1% of which was recompilation)

julia> @time combine(groupby(ds, :x1), :x2 => [IMD.sum, mean]);
  1.873588 seconds (2.45 M allocations: 131.094 MiB, 4.56% gc time, 99.76% compilation time: 1% of which was recompilation)

julia> @time leftjoin(ds, ds1, on = :x1);
  2.502575 seconds (743.21 k allocations: 128.354 MiB, 3.04% gc time, 95.88% compilation time: 0% of which was recompilation)

julia> @time update(ds, ds1, on = [:x1, :x2]);
  2.381686 seconds (1.87 M allocations: 187.412 MiB, 3.47% gc time, 95.46% compilation time: 1% of which was recompilation)

julia> @time transpose(ds, :);
  1.046670 seconds (2.27 M allocations: 299.527 MiB, 8.31% gc time, 77.41% compilation time: 2% of which was recompilation)
```

**Comment by sl-solution** [comment]
I see, you mean @snoopi is doing well, we do not need @snoopc.

Please add a comment in the file that shows the steps to create the precompilation script

**Comment by sl-solution** [comment]
One more thing, make sure that precompilation does not have any effect on older Julia release, i.e. no extra allocation and no latency improvement

**Comment by Nayoth** [comment]
The precompile causes extra allocation for older Julia releases, so the precompile statements are only running for Julia v1.8.

**Pull request merged**
