### PR TITLE
improve the performance of `DLMReader.jl` write

### PR DESCRIPTION
**Pull request by giantmoa**
This improves the performance of `filewriter` in `DLMReader.jl` when `mapformats=true`.

### CODE REVIEW

**Comment by sl-solution** [comment]
Great! please add some tests. You may want to add the test sets in `DLMReader`.

**Comment by sl-solution** [comment]
Please also check that this works for wide table.

**Comment by giantmoa** [comment]
I checked wide data sets, and unfortunately, this needs more work.

**Comment by sl-solution** [comment]
The problem here is that using `ntuple` causes compilers optimise the code for few columns, however, the compiler gives up the optimisation when there are too many columns. I guess you can use the function barrier technique to improve this, i.e. put line 225--258 into a new function and only pass the corresponding element of `f` to it (thus, compiler can manage optimisation).

**Comment by giantmoa** [comment]
There is a bug when `quotechar` is passed, so I change the `row_join!` to fix it too.

**Comment by sl-solution** [comment]
> There is a bug when `quotechar` is passed, so I change the `row_join!` to fix it too.

Probably we can check the return type, however, it should be too much allocation. I guess this seems ok.

Anyway, PR seems great!

**Pull request merged**
